.github/workflows/lint.yaml
.vale.ini
styles/config/vocabularies/coco/accept.txt

This is useful to smoothen the review of submissions and the overall quality of the content.
Vale is able to use certain comprehensive style guides (e.g. Redhat, Microsoft, Google). This PR just uses merely the base check, which already produces some good findings.
We can decide on a more opinionated style guide later.

ci: add prose linting with vale

---

content/en/docs/demos/ccv0-operator-demo.md
content/en/docs/demos/ssh-demo/index.md

- Fix broken links
- Update links to old branches to new branches
- Add worker node label command
- FIx typos
- Add `--progress=plain` to `docker build` so the user can see the key fingerprint
- Remove the "adaptation" warning because they have been tested and verified now
I haven't tried the kcli setup example nor the crictl configuration for port forwarding.
The `katadocker/ccv0-ssh` demo image didn't work for me as explained in the instructions because they don't explain how to set up an attestation-agent. We can address that part in a follow-up PR.

demos: fix SSH and operator demo documentation

---

content/en/docs/use-cases/_index.md
content/en/docs/use-cases/encrypted-images.md

- Added subsection "use cases"
- Added a use case "image encryption" with coco

docs: add encrypted image use case

---

content/en/docs/cloud-api-adaptor/azure/_index.md

Recently CAA repo was restructured so some steps may not work because of that. So this commit updates those steps.

Azure: Update steps with recent repo restructuring

---

hugo.yaml

Setup Google analytics on the website. Before we start a big push on website content, let's setup analytics so we know if anyone is looking at the site and which pages they are most interested in. 
Unfortunately we don't have a great way to hook google analytics into our github organization. This property is linked to my google account, but it can be shared with anyone else's google account. Lmk if there is a better way to handle this.

Add Analytics

---

layouts/_default/_markup/render-heading.html

This lets us share links to specific header sections within the docs, which is a nice-to-have.

Add support for links to headers and subheaders

---

hugo.yaml

This uses the Lunr.js functionality that's part of our website framework. It's an offline javascript-based search (not using Google, for example). Seems to work fine.
It adds a search bar above the navigation on the left-hand side, and it adds a search bar in the top right. The one above the navigation bar can be disabled if we want, but I left it there.

Enable basic search support across the site

---

content/en/docs/features/authenticated-registries.md

Explain how to configure for using authenticated registries.
Related-to: #52
---
I tested the instructions locally.
In my explanation to why a `docker-registry` secret is needed, the culprint is nydus-snapshotter. But in reality I don't remember whether it's him or containerd (or both) that requires the credentials. So please check the information is accurate.

features: add authenticated registries documentation

---

content/en/docs/getting-started/prerequisites/hardware/snp.md

Adding the required prerequisites to run CoCo using SEV-SNP.

Docs: adding SNP prerequisites to CoCo website

---

hugo.yaml

Make description more verbose to capture scope of project.
Really, this is for SEO. Hugo already populates various metadata tags, so we don't need to (and shouldn't) do too much, but maybe this will help.
@ariel-adam

config: make description more verbose

---

content/en/docs/architecture/design-overview.md
content/en/docs/architecture/trust-model/trust-model.md

Fix a couple minor typos in the architecture pages.

docs: fix typos

---

content/en/docs/features/signed-images.md
styles/config/vocabularies/coco/accept.txt

This doc provides a very brief overview of the purpose of signed images. Then it details the steps (generating keys, signing, and updating KBS) for both cosign and "simple signing."

Docs for signed images

---

content/en/docs/features/get-attestation.md
content/en/docs/features/get-resource.md

It's a bit tricky to address the evidence factory stuff, but hopefully the note there is useful.

Add feature pages for the REST API (resources and attestation)

---

content/en/docs/getting-started/workload.md

The simple workload instructions were copied from the quickstart guide in GitHub. There are a few issues.
They refer to an old method of checking that the container is not present on the host. Remove this. There is another method for checking, but it's probably too advanced to live on this page.
They link to the guides page, which doesn't exist on the website.

docs: fix old information in getting-started guide

---

content/en/docs/examples/snp-container-launch.md

Moving the example of launching a container with SNP from the [confidential-containers SNP](https://github.com/arvindskumar99/confidential-containers-arvind/blob/kata_snp_instr/guides/snp.md) guide to the website to deprecate the old guide.

Example of launching a container with SNP

---

content/en/docs/examples/azure-simple.md

In the latest-build tabs of the instructions we reference an outdated workflow.
thx @ldoktor for reporting this

azure: update reference to workflow

---

content/en/docs/features/encrypted-images.md
styles/config/vocabularies/coco/accept.txt

Many users struggle with using encrypted images. This is an attempt to consolidate the various slack tracks into a comprehensive step-by-step guide.

docs: add debug section to encrypted images page

---

content/en/docs/attestation/installation/kubernetes.md

- Links now pointing to newly published blog: https://confidentialcontainers.org/blog/2025/02/19/deploy-trustee-in-kubernetes/
- updated documentation to use "operators" namespace

Fix trustee-operator doc

---

content/en/docs/getting-started/prerequisites/hardware/snp.md

Updating the SNP documentation to include references to the new kernel and upstream components.

Updating SNP docs to use new instructions/tags for upstream components

---

content/en/docs/examples/aws-simple.md

Fix the overlays folder to point to `aws` and update the release version to 0.13.0

aws: Fix incorrect folder and update release version

---

content/en/docs/attestation/installation/kubernetes.md

By default, the operator deploys a trustee v0.11.0-based image. A note was added in the Trustee Operator deployment guide for overriding the image with an updated one.

Add note for overriding the default trustee image

---

content/en/docs/attestation/policies/_index.md

Now that we're about to release CoCo with multi-device support, let's update our example policies to use `cpu0` rather than `cpu`.

docs: update policies for multi-device
